### ISSUE TITLE
Unrecognized option: --username

### ISSUE THREAD

**Issue by arnolde** [iiiypuk/minecraft-launcher#15]
Hi, thank you very much for writing this! I've been looking all day for a "just run it!" script.

Unfortunately I get:
```
ea@Q520:~/Downloads$ bash ./mc_start.sh 
What username would you like?: Ethan
Unrecognized option: --username
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

BTW I also found out how to get a valid token: https://wiki.vg/Authentication - so together with this we could run the game with a valid token.

**Comment by arnolde** [comment]
Meanwhile I found the make_libs_list.py but I have no version.json (on Ubuntu 18.04 Linux) anywhere... it returns:
```ea@Q520:~/.minecraft$ ./make_libs_list.py 
Traceback (most recent call last):
  File "./make_libs_list.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Comment by iiiypuk** [comment]
> ModuleNotFoundError: No module named 'click'

Install requirements from `requirements.txt`
`pip install -r requirements.txt`

**Comment by iiiypuk** [comment]
> Unrecognized option: --username

Now I downloaded the latest release (1.16.5), unpacked the binary packages and the script started without errors. 
```
PS C:\Users\alex> java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
```

**Comment by iiiypuk** [comment]
*UPD:* Version from `master` also working.

**Comment by iiiypuk** [comment]
Check again and tell us about the result.

**Comment by arnolde** [comment]
I'm sorry, meanwhile I found this, which runs perfectly for me so I'm just using that:
https://stackoverflow.com/questions/14531917/launch-minecraft-from-command-line-username-and-password-as-prefix
