### ISSUE TITLE
Update the README for beginners

### ISSUE THREAD

**Issue by Ka-hu** [iiiypuk/minecraft-launcher#19]
First of all, thanks for this script.
But please consider adding some information about the setup for beginners. I wasn't sure why it wasn't working for me, and, as it turned out because I didn't have the natives in the ~/.minecraft/bin folder. For those who are not experienced in Minecraft launchers and/or modding, a step by step guide would be useful, something like this for example:

## Usage
- Download the zip from the [releases](https://github.com/iiiypuk/minecraft-launcher/releases) page (**important**: select the version that matches your Minecraft version. Different versions are incompatible!)
- Download the natives zip file from [Mega.nz](https://mega.nz/#F!hUNg0Y6I!93cYw1NZg4MUWUHaVrCO7w) (**important**: select the version that matches your Minecraft version. Different versions are incompatible!)
- Extract the natives zip file to the bin folder inside the Minecraft folder (`~/.minecraft/bin` on Linux)
- Extract the launcher's zip file and run the launcher (`mc_start.sh` on Linux or `mc_start.bat` on Windows)

**Comment by iiiypuk** [comment]
Thanks for your feedback. There is a manual at the moment, but only in [Russian](https://github.com/iiiypuk/minecraft-launcher/blob/gh-pages/docs/installing.md).
The documentation is available on the [website](http://iiiypuk.github.io/minecraft-launcher/), and [gh-pages](https://github.com/iiiypuk/minecraft-launcher/tree/gh-pages) branch.

At the end of the month, I will have free time and I will start filling out the documentation, translating it, and also collecting distributions  vanilla and forge versions.

**Comment by iiiypuk** [comment]
Complete =)

[Online guide](https://iiiypuk.github.io/minecraft-launcher/#/en-us/installing) ([Russian](https://iiiypuk.github.io/minecraft-launcher/#/installing)).

[Commit](https://github.com/iiiypuk/minecraft-launcher/commit/cf0e936872d413bfcbeb53a09bcdd06c8e750716#diff-46b42b4229cd7a39c564e780bb665a8bde4fdf722007e8473f167fe53ed4b995).
