### ISSUE TITLE
Конфигурационный файл

### ISSUE THREAD

**Issue by iiiypuk** [iiiypuk/minecraft-launcher#2]
Добавить в скрипт файл конфигурации, который настраивается при первом запуске

**Comment by scpketer** [comment]
Working, wait for PR soon ;)

**Comment by iiiypuk** [comment]
No need now [[5a80655](https://github.com/iiiypuk/minecraft-launcher/commit/5a806555d580e2e58188b5aae7fa84265a9bc172)]
See `REDME.md`
> No need configuration
