### ISSUE TITLE
Exception in thread "main" joptsimple.MissingRequiredOptionsException: Missing required option(s) [version]    

### ISSUE THREAD

**Issue by RobinD3l** [iiiypuk/minecraft-launcher#22]
Hello,

i followed all the steps but i cant get it to work. When i add "pause" at the end so that the cmd doesnt close it gives me the following error: Exception in thread "main" joptsimple.MissingRequiredOptionsException: Missing required option(s) [version]
        at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
        at joptsimple.OptionParser.parse(OptionParser.java:400)
        at net.minecraft.client.main.Main.main(SourceFile:79)

**Comment by iiiypuk** [comment]
show your line
`set GAME_VERSION=`

**Comment by RobinD3l** [comment]
This is my current .bat file i extracted all the natives into the .bin folder like this: [](https://i.imgur.com/eHhoEpx.png)

rem @echo off
title Minecraft Launcher

:: set username
set /p player=xxx

:: main directory of the game
set MC_DIR=%APPDATA%\.minecraft

:: Are stored here...
:: saves/, resourcepacks/ and screenshots/ dirs
:: and options.txt and servers.dat files
set GAME_DIR=%MC_DIR%

:: libraries and resource dir (requires no changes)
set ASSETS_DIR=%MC_DIR%\assets
set ASSETS_INDEX=1.16

:: version minecraft (from versions/ dir)
set GAME_VERSION=1.16.5

:: get archive from natives/ dir
set NATIVES_DIR=%MC_DIR%\bin\%GAME_VERSION%

:: player nickname (the over head)
set PLAYER_NAME=%player%

:: game window resolution
set WINDOW_W=800
set WINDOW_H=640

:: java machine arguments
set "JVM_RAM=-Xmx2G"
set "JVM_ARGS=-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"

:: running minecraft
%SystemDrive%
cd %MC_DIR%

java.exe %JVM_RAM% %JVM_ARGS% ^
-Djava.library.path=%NATIVES_DIR% ^
-cp %MC_DIR%/libraries/com/mojang/patchy/1.1/patchy-1.1.jar;%MC_DIR%/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar;%MC_DIR%/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar;%MC_DIR%/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar;%MC_DIR%/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar;%MC_DIR%/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar;%MC_DIR%/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar;%MC_DIR%/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar;%MC_DIR%/libraries/com/google/guava/guava/21.0/guava-21.0.jar;%MC_DIR%/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar;%MC_DIR%/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar;%MC_DIR%/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar;%MC_DIR%/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar;%MC_DIR%/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar;%MC_DIR%/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar;%MC_DIR%/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar;%MC_DIR%/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar;%MC_DIR%/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar;%MC_DIR%/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar;%MC_DIR%/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar;%MC_DIR%/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar;%MC_DIR%/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar;%MC_DIR%/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar;%MC_DIR%/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar;%MC_DIR%/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-tinyfd/3.2.1/lwjgl-tinyfd-3.2.1.jar;%MC_DIR%/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar;%MC_DIR%/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar;%MC_DIR%/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar;%MC_DIR%/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar;%MC_DIR%/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar;%MC_DIR%/versions/%GAME_VERSION%/%GAME_VERSION%.jar ^
net.minecraft.client.main.Main ^
--username %PLAYER_NAME% ^
--version %GAME_VERSION% ^
--accessToken 0 --userProperties {} ^
--gameDir %GAME_DIR% ^
--assetsDir %ASSETS_DIR% ^
--assetIndex %ASSETS_INDEX% ^
--width %WINDOW_W% ^
--height %WINDOW_H%
pause

**Comment by iiiypuk** [comment]
Error in your paths:
Change
```
set MC_DIR=%APPDATA%.minecraft
set NATIVES_DIR=%MC_DIR%\bin%GAME_VERSION%
````

```
set MC_DIR=%APPDATA%\.minecraft
set NATIVES_DIR=%MC_DIR%\bin\%GAME_VERSION%
````

**Comment by iiiypuk** [comment]
Your edits:
```
:: set username
set /p player=xxx
```
See [this](https://iiiypuk.github.io/minecraft-launcher/#/en-us/variables?id=player_name) guide for true using.
> By default, when the script starts, the user is prompted to enter the player's name interactively.
> If there is no need to change the name when starting the script, write down the required name in the variable.
> set PLAYER_NAME=Steve
> and remove this line
> set /p player=What username would you like?

**Comment by RobinD3l** [comment]
I removed the line set /p player=xxx and changed %player% to my username and now it is working thanks for your reply
