### ISSUE TITLE
Проблемы с запуском под GNU/Linux

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [iiiypuk/minecraft-launcher#9]
Classpath нужно обернуть в кавычки, иначе баш разделит строку по ;
Даже с classpath в кавычках всё равно не запускается, выводит ошибку
`Error: Could not find or load main class net.minecraft.client.main.Main`

**Comment by iiiypuk** [comment]
Попробуй с этим лаунчером.
https://yadi.sk/d/sHFYFY2ALtpBHw
